import './globals.css';
import { Inter, Poppins } from 'next/font/google';
import Navbar from '@/components/navbar';

const poppins = Poppins({ 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  subsets: ['devanagari']
})

export const metadata = {
  title: 'Independence Day Wisher Online',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
