import './globals.css';
import Navbar from '@/components/navbar';

export const metadata = {
  title: 'Independence Day Wisher Online',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        </body>
    </html>
  )
}