import Link from 'next/link';
import styles from '@/styles/pages.module.css';

export const metadata = {
  title: '404 | Page Not Found - Independence Day Wisher Online',
  description: 'Generated by create next app',
}

export default function NotFound() {
  return (
    <div className={styles.errorContainer}>
      <div className={styles.errorImage}>
        <img src="/404.svg" alt="404 Error Illustration" />
      </div>
      <div className={styles.errorContent}>
        <h2 className={styles.errorHeading}>404 - Page Not Found</h2>
        <p className={styles.errorText}>
          Oops! It seems like the page you're looking for doesn't exist.
        </p>
        <Link href="/">
          <button>Return to Home</button>
        </Link>
      </div>
    </div>
  );
}